<?php

namespace Database\Seeders;

use App\Models\Products;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'product_name' => 'Flagship iPhone 15 Pro Max',
                'cate_id' => 1,
                'brand_id' => 1,
                'color_id' => 1,
                'product_img' => 'Iphone.jpg',
                'regular_price' => 1199.99,
                'sale_price' => 1099.99,
                'quantity' => 25,
                'materials' => 'Titanium & Glass',
                'type' => 'Smartphone',
                'storage' => '256GB',
                'RAM' => '8GB',
                'quantity_sold' => 40,
                'status' => 'In Stock',
                'descriptions' => 'Super Retina XDR display with ProMotion. A17 Pro chip with 6-core GPU. Powerful Pro camera system.',
            ],
            [
                'id' => 2,
                'product_name' => 'Samsung Galaxy S24 Ultra 5G',
                'cate_id' => 1,
                'brand_id' => 2,
                'color_id' => 2,
                'product_img' => 'mobile.jpg',
                'regular_price' => 1299.99,
                'sale_price' => 1149.99,
                'quantity' => 18,
                'materials' => 'Armor Aluminum',
                'type' => 'Smartphone',
                'storage' => '512GB',
                'RAM' => '12GB',
                'quantity_sold' => 30,
                'status' => 'In Stock',
                'descriptions' => 'Galaxy AI power, 200MP camera, Snapdragon 8 Gen 3 for Galaxy, Built-in S Pen.',
            ],
            [
                'id' => 3,
                'product_name' => 'ROG Strix High Performance Gaming Laptop',
                'cate_id' => 2,
                'brand_id' => 3,
                'color_id' => 1,
                'product_img' => 'laptop.jpg',
                'regular_price' => 1799.99,
                'sale_price' => 1599.99,
                'quantity' => 12,
                'materials' => 'Magnesium Alloy',
                'type' => 'Gaming Laptop',
                'storage' => '1TB NVMe SSD',
                'RAM' => '32GB DDR5',
                'quantity_sold' => 15,
                'status' => 'In Stock',
                'descriptions' => 'Intel Core i9 14900HX, NVIDIA GeForce RTX 4080 12GB, 240Hz QHD+ display.',
            ],
            [
                'id' => 4,
                'product_name' => 'MacBook Pro 16-inch M3 Max',
                'cate_id' => 2,
                'brand_id' => 1,
                'color_id' => 2,
                'product_img' => 'laptop1.png',
                'regular_price' => 2499.99,
                'sale_price' => 2299.99,
                'quantity' => 10,
                'materials' => '100% Recycled Aluminum',
                'type' => 'Professional Laptop',
                'storage' => '1TB SSD',
                'RAM' => '36GB Unified',
                'quantity_sold' => 20,
                'status' => 'In Stock',
                'descriptions' => 'Liquid Retina XDR display, up to 22 hours battery life, 16-core CPU, 40-core GPU.',
            ],
            [
                'id' => 5,
                'product_name' => 'Dell XPS 15 Touchscreen Workstation',
                'cate_id' => 2,
                'brand_id' => 4,
                'color_id' => 2,
                'product_img' => 'pc.jpg',
                'regular_price' => 1599.99,
                'sale_price' => 1399.99,
                'quantity' => 15,
                'materials' => 'CNC Machined Aluminum',
                'type' => 'Workstation',
                'storage' => '512GB SSD',
                'RAM' => '16GB DDR5',
                'quantity_sold' => 18,
                'status' => 'In Stock',
                'descriptions' => '3.5K OLED touch display, Intel Core i7 13700H, RTX 4060 graphics.',
            ],
            [
                'id' => 6,
                'product_name' => 'Over-Ear Active Noise Canceling Headphones',
                'cate_id' => 6,
                'brand_id' => 8,
                'color_id' => 1,
                'product_img' => 'bluetoothheadphone.jpg',
                'regular_price' => 299.99,
                'sale_price' => 239.99,
                'quantity' => 40,
                'materials' => 'Memory Foam & Leather',
                'type' => 'Wireless Headphones',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 75,
                'status' => 'In Stock',
                'descriptions' => 'Industry-leading noise canceling with dual noise sensor technology, 30-hour battery life.',
            ],
            [
                'id' => 7,
                'product_name' => 'JBL Wireless Portable Bluetooth Speaker',
                'cate_id' => 6,
                'brand_id' => 8,
                'color_id' => 3,
                'product_img' => 'Speaker.jpg',
                'regular_price' => 129.99,
                'sale_price' => 99.99,
                'quantity' => 50,
                'materials' => 'Durable Fabric & Rubber',
                'type' => 'Portable Speaker',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 110,
                'status' => 'In Stock',
                'descriptions' => 'IP67 waterproof and dustproof, 12 hours playtime, punchy JBL Original Pro Sound.',
            ],
            [
                'id' => 8,
                'product_name' => 'Fast Charging Power Bank 20000mAh',
                'cate_id' => 3,
                'brand_id' => 7,
                'color_id' => 1,
                'product_img' => 'BackupCharger.png',
                'regular_price' => 59.99,
                'sale_price' => 45.99,
                'quantity' => 60,
                'materials' => 'Fireproof Polycarbonate',
                'type' => 'Power Bank',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 130,
                'status' => 'In Stock',
                'descriptions' => '65W Power Delivery fast charging for laptops, phones, and tablets with digital LED display.',
            ],
            [
                'id' => 9,
                'product_name' => 'Ultra HD 4K Curved Desktop Monitor 32-inch',
                'cate_id' => 5,
                'brand_id' => 3,
                'color_id' => 1,
                'product_img' => 'monitors.jpg',
                'regular_price' => 549.99,
                'sale_price' => 449.99,
                'quantity' => 14,
                'materials' => 'Matte Polymer',
                'type' => 'Desktop Monitor',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 22,
                'status' => 'In Stock',
                'descriptions' => '1500R curvature, 144Hz refresh rate, 1ms response time, HDR10 support.',
            ],
            [
                'id' => 10,
                'product_name' => 'Ergonomic Wireless RGB Gaming Mouse',
                'cate_id' => 3,
                'brand_id' => 3,
                'color_id' => 1,
                'product_img' => 'mouses.jpg',
                'regular_price' => 89.99,
                'sale_price' => 69.99,
                'quantity' => 45,
                'materials' => 'Textured ABS Plastic',
                'type' => 'Gaming Mouse',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 95,
                'status' => 'In Stock',
                'descriptions' => '26,000 DPI optical sensor, ultra-lightweight 59g body, custom programmable buttons.',
            ],
            [
                'id' => 11,
                'product_name' => 'Mechanical Wireless RGB Keyboard',
                'cate_id' => 3,
                'brand_id' => 3,
                'color_id' => 1,
                'product_img' => 'Keyborads.jpg',
                'regular_price' => 149.99,
                'sale_price' => 119.99,
                'quantity' => 30,
                'materials' => 'Anodized Aluminum Plate',
                'type' => 'Mechanical Keyboard',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 65,
                'status' => 'In Stock',
                'descriptions' => 'Hot-swappable switches, PBT double-shot keycaps, tri-mode wireless & Bluetooth connectivity.',
            ],
            [
                'id' => 12,
                'product_name' => 'iPad Pro 12.9-inch M2 Chip',
                'cate_id' => 4,
                'brand_id' => 1,
                'color_id' => 2,
                'product_img' => 'tablet.jpg',
                'regular_price' => 1099.99,
                'sale_price' => 999.99,
                'quantity' => 20,
                'materials' => 'Recycled Aluminum',
                'type' => 'Tablet',
                'storage' => '256GB',
                'RAM' => '8GB',
                'quantity_sold' => 35,
                'status' => 'In Stock',
                'descriptions' => 'Liquid Retina XDR display, M2 chip, Apple Pencil hover, 12MP Ultra Wide front camera.',
            ],
            [
                'id' => 13,
                'product_name' => 'Baseus High Speed USB-C Multi Hub',
                'cate_id' => 3,
                'brand_id' => 7,
                'color_id' => 2,
                'product_img' => 'Hubs.jpg',
                'regular_price' => 49.99,
                'sale_price' => 39.99,
                'quantity' => 50,
                'materials' => 'Aluminum Alloy',
                'type' => 'USB Hub',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 88,
                'status' => 'In Stock',
                'descriptions' => '8-in-1 expansion with 4K HDMI, 100W PD charging, SD card reader, 3x USB 3.0 ports.',
            ],
            [
                'id' => 14,
                'product_name' => 'High Speed Wi-Fi 6 Mesh Router',
                'cate_id' => 5,
                'brand_id' => 3,
                'color_id' => 5,
                'product_img' => 'routers.jpg',
                'regular_price' => 199.99,
                'sale_price' => 159.99,
                'quantity' => 25,
                'materials' => 'ABS Synthetic',
                'type' => 'Networking',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 40,
                'status' => 'In Stock',
                'descriptions' => 'Dual-band Wi-Fi 6 speed up to 3000 Mbps, seamless mesh coverage up to 5,000 sq ft.',
            ],
            [
                'id' => 15,
                'product_name' => 'Computer Mac & Peripheral Accessories Package',
                'cate_id' => 3,
                'brand_id' => 1,
                'color_id' => 2,
                'product_img' => 'sp1.jpg',
                'regular_price' => 199.99,
                'sale_price' => 179.99,
                'quantity' => 35,
                'materials' => 'Composite Materials',
                'type' => 'Accessories',
                'storage' => '256GB',
                'RAM' => '8GB',
                'quantity_sold' => 50,
                'status' => 'In Stock',
                'descriptions' => 'Essential computer accessories for Mac desktop setup including charging cables and adapters.',
            ],
            [
                'id' => 16,
                'product_name' => 'Premium Leather Laptop Backpack',
                'cate_id' => 3,
                'brand_id' => 7,
                'color_id' => 1,
                'product_img' => 'balos.jpg',
                'regular_price' => 79.99,
                'sale_price' => 59.99,
                'quantity' => 40,
                'materials' => 'Waterproof Leatherette',
                'type' => 'Carrying Case',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 70,
                'status' => 'In Stock',
                'descriptions' => 'Fits up to 16-inch laptops with anti-theft hidden pocket and built-in USB charging port.',
            ],
            [
                'id' => 17,
                'product_name' => 'Samsung Galaxy Tab S9 Ultra',
                'cate_id' => 4,
                'brand_id' => 2,
                'color_id' => 1,
                'product_img' => 'tablet.jpg',
                'regular_price' => 1199.99,
                'sale_price' => 1049.99,
                'quantity' => 15,
                'materials' => 'Armor Aluminum',
                'type' => 'Tablet',
                'storage' => '512GB',
                'RAM' => '12GB',
                'quantity_sold' => 25,
                'status' => 'In Stock',
                'descriptions' => '14.6-inch Dynamic AMOLED 2X display, IP68 water resistance, S Pen included.',
            ],
            [
                'id' => 18,
                'product_name' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'cate_id' => 2,
                'brand_id' => 5,
                'color_id' => 1,
                'product_img' => 'laptop.jpg',
                'regular_price' => 1699.99,
                'sale_price' => 1499.99,
                'quantity' => 12,
                'materials' => 'Carbon Fiber weave',
                'type' => 'Business Laptop',
                'storage' => '1TB SSD',
                'RAM' => '32GB LPDDR5',
                'quantity_sold' => 22,
                'status' => 'In Stock',
                'descriptions' => 'Ultra-lightweight 1.12kg business laptop, Intel vPro platform, legendary ThinkPad keyboard.',
            ],
            [
                'id' => 19,
                'product_name' => 'Xiaomi Redmi Note 13 Pro+ 5G',
                'cate_id' => 1,
                'brand_id' => 6,
                'color_id' => 3,
                'product_img' => 'mobile.jpg',
                'regular_price' => 499.99,
                'sale_price' => 399.99,
                'quantity' => 30,
                'materials' => 'Glass back & Metal frame',
                'type' => 'Smartphone',
                'storage' => '256GB',
                'RAM' => '12GB',
                'quantity_sold' => 80,
                'status' => 'In Stock',
                'descriptions' => '200MP OIS camera, 120W HyperCharge, IP68 dust and water resistance, 120Hz 1.5K AMOLED display.',
            ],
            [
                'id' => 20,
                'product_name' => 'High Capacity External SSD 2TB',
                'cate_id' => 3,
                'brand_id' => 2,
                'color_id' => 2,
                'product_img' => 'Drive.jpg',
                'regular_price' => 179.99,
                'sale_price' => 149.99,
                'quantity' => 40,
                'materials' => 'Shockproof Rubberized Shield',
                'type' => 'Storage',
                'storage' => '2TB External',
                'RAM' => 'N/A',
                'quantity_sold' => 90,
                'status' => 'In Stock',
                'descriptions' => 'Read speeds up to 1050 MB/s, drop-resistant up to 2 meters, USB 3.2 Gen 2 connectivity.',
            ],
            [
                'id' => 21,
                'product_name' => 'Wired Hi-Res Studio Headphones',
                'cate_id' => 6,
                'brand_id' => 8,
                'color_id' => 1,
                'product_img' => 'wired-headphones.jpg',
                'regular_price' => 149.99,
                'sale_price' => 119.99,
                'quantity' => 25,
                'materials' => 'Stainless Steel Headband',
                'type' => 'Studio Headphones',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 45,
                'status' => 'In Stock',
                'descriptions' => '50mm neodymium drivers for precision monitoring audio, detachable oxygen-free copper cable.',
            ],
            [
                'id' => 22,
                'product_name' => 'Baseus Magnetic Wireless Charger Stand',
                'cate_id' => 3,
                'brand_id' => 7,
                'color_id' => 5,
                'product_img' => 'ChargerCable.jpg',
                'regular_price' => 39.99,
                'sale_price' => 29.99,
                'quantity' => 60,
                'materials' => 'Aluminum & Silicone',
                'type' => 'Wireless Charger',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 140,
                'status' => 'In Stock',
                'descriptions' => '15W MagSafe compatible fast wireless charging stand for iPhone and AirPods simultaneously.',
            ],
            [
                'id' => 23,
                'product_name' => 'High Speed MicroSDXC Memory Card 512GB',
                'cate_id' => 3,
                'brand_id' => 2,
                'color_id' => 1,
                'product_img' => 'micros.jpg',
                'regular_price' => 69.99,
                'sale_price' => 49.99,
                'quantity' => 70,
                'materials' => 'Silicon Wafer',
                'type' => 'Memory Card',
                'storage' => '512GB',
                'RAM' => 'N/A',
                'quantity_sold' => 180,
                'status' => 'In Stock',
                'descriptions' => 'V30 4K UHD video recording speed, up to 160MB/s transfer speeds for cameras and Nintendo Switch.',
            ],
            [
                'id' => 24,
                'product_name' => 'Rugged Armor Protective Phone Case',
                'cate_id' => 3,
                'brand_id' => 7,
                'color_id' => 1,
                'product_img' => 'cases.jpg',
                'regular_price' => 29.99,
                'sale_price' => 19.99,
                'quantity' => 80,
                'materials' => 'TPU & Polycarbonate',
                'type' => 'Protection',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 210,
                'status' => 'In Stock',
                'descriptions' => 'Military-grade drop protection with tactile buttons and raised camera lens bezel.',
            ],
            [
                'id' => 25,
                'product_name' => 'Asus ZenBook 14 OLED Slim Ultrabook',
                'cate_id' => 2,
                'brand_id' => 3,
                'color_id' => 3,
                'product_img' => 'laptop.jpg',
                'regular_price' => 1099.99,
                'sale_price' => 949.99,
                'quantity' => 22,
                'materials' => 'Aluminum Unibody',
                'type' => 'Ultrabook',
                'storage' => '512GB NVMe SSD',
                'RAM' => '16GB LPDDR5',
                'quantity_sold' => 32,
                'status' => 'In Stock',
                'descriptions' => '14-inch 2.8K 90Hz OLED display, Intel Core Ultra 7 processor, Harman Kardon sound.',
            ],
            [
                'id' => 26,
                'product_name' => 'iPhone 14 Plus 128GB - Starlight',
                'cate_id' => 1,
                'brand_id' => 1,
                'color_id' => 5,
                'product_img' => 'Iphone.jpg',
                'regular_price' => 899.99,
                'sale_price' => 799.99,
                'quantity' => 30,
                'materials' => 'Aerospace-grade Aluminum',
                'type' => 'Smartphone',
                'storage' => '128GB',
                'RAM' => '6GB',
                'quantity_sold' => 60,
                'status' => 'In Stock',
                'descriptions' => '6.7-inch Super Retina XDR display, advanced dual-camera system, All-day battery life.',
            ],
            [
                'id' => 27,
                'product_name' => 'Dell UltraSharp 27 4K USB-C Monitor',
                'cate_id' => 5,
                'brand_id' => 4,
                'color_id' => 2,
                'product_img' => 'monitors.jpg',
                'regular_price' => 619.99,
                'sale_price' => 529.99,
                'quantity' => 16,
                'materials' => 'Recycled Plastics & Aluminum',
                'type' => 'Monitor',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 28,
                'status' => 'In Stock',
                'descriptions' => 'IPS Black technology with 2000:1 contrast ratio, 100% sRGB & 98% DCI-P3 color gamut.',
            ],
            [
                'id' => 28,
                'product_name' => 'Xiaomi Pad 6 11-inch 144Hz WQHD+',
                'cate_id' => 4,
                'brand_id' => 6,
                'color_id' => 2,
                'product_img' => 'tablet.jpg',
                'regular_price' => 399.99,
                'sale_price' => 329.99,
                'quantity' => 35,
                'materials' => 'Metal Unibody',
                'type' => 'Tablet',
                'storage' => '128GB',
                'RAM' => '8GB',
                'quantity_sold' => 75,
                'status' => 'In Stock',
                'descriptions' => 'Snapdragon 870 processor, Quad speakers with Dolby Atmos, 8840mAh battery.',
            ],
            [
                'id' => 29,
                'product_name' => 'Baseus GaN 65W Fast Wall Charger',
                'cate_id' => 3,
                'brand_id' => 7,
                'color_id' => 5,
                'product_img' => 'ChargerCable.jpg',
                'regular_price' => 45.99,
                'sale_price' => 34.99,
                'quantity' => 80,
                'materials' => 'GaN Technology',
                'type' => 'Charger',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 190,
                'status' => 'In Stock',
                'descriptions' => 'Compact 3-port GaN charger supporting Quick Charge 4.0+ and PD 3.0 for laptops and phones.',
            ],
            [
                'id' => 30,
                'product_name' => 'Samsung Galaxy Buds2 Pro True Wireless',
                'cate_id' => 6,
                'brand_id' => 2,
                'color_id' => 1,
                'product_img' => 'bluetoothheadphone.jpg',
                'regular_price' => 229.99,
                'sale_price' => 179.99,
                'quantity' => 45,
                'materials' => 'Matte Polymer',
                'type' => 'Earbuds',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 120,
                'status' => 'In Stock',
                'descriptions' => '24-bit Hi-Fi audio, Intelligent 360 Audio with direct multi-channel, IPX7 water resistance.',
            ],
            [
                'id' => 31,
                'product_name' => 'Lenovo Legion Tower 5i Gaming Desktop',
                'cate_id' => 5,
                'brand_id' => 5,
                'color_id' => 1,
                'product_img' => 'pc.jpg',
                'regular_price' => 1399.99,
                'sale_price' => 1249.99,
                'quantity' => 10,
                'materials' => 'Steel Chassis with Tempered Glass',
                'type' => 'Gaming PC',
                'storage' => '1TB Gen4 SSD',
                'RAM' => '16GB DDR5',
                'quantity_sold' => 14,
                'status' => 'In Stock',
                'descriptions' => '13th Gen Intel Core i7, NVIDIA GeForce RTX 4070 12GB, ARGB liquid cooling.',
            ],
            [
                'id' => 32,
                'product_name' => 'Xiaomi Smart Band 8 Pro Fitness Tracker',
                'cate_id' => 3,
                'brand_id' => 6,
                'color_id' => 1,
                'product_img' => 'sp1.jpg',
                'regular_price' => 89.99,
                'sale_price' => 69.99,
                'quantity' => 50,
                'materials' => 'Metallic NCVM frame',
                'type' => 'Fitness Tracker',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 160,
                'status' => 'In Stock',
                'descriptions' => '1.74-inch AMOLED display, built-in GNSS GPS tracking, 14-day battery life.',
            ],
            [
                'id' => 33,
                'product_name' => 'Asus ROG Swift 27-inch 240Hz Gaming Monitor',
                'cate_id' => 5,
                'brand_id' => 3,
                'color_id' => 1,
                'product_img' => 'monitors.jpg',
                'regular_price' => 699.99,
                'sale_price' => 599.99,
                'quantity' => 12,
                'materials' => 'Textured Polymer',
                'type' => 'Gaming Monitor',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 20,
                'status' => 'In Stock',
                'descriptions' => 'QHD 2560x1440 Fast IPS panel, G-SYNC compatible, DisplayHDR 400 certified.',
            ],
            [
                'id' => 34,
                'product_name' => 'Apple Magic Keyboard for iPad Pro 12.9',
                'cate_id' => 3,
                'brand_id' => 1,
                'color_id' => 1,
                'product_img' => 'Keyborads.jpg',
                'regular_price' => 349.99,
                'sale_price' => 299.99,
                'quantity' => 20,
                'materials' => 'Polyurethane & Aluminum',
                'type' => 'Keyboard Case',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 38,
                'status' => 'In Stock',
                'descriptions' => 'Floating cantilever design, backlit keys, scissor mechanism with 1mm travel, trackpad.',
            ],
            [
                'id' => 35,
                'product_name' => 'JBL PartyBox Club 120 High Power Speaker',
                'cate_id' => 6,
                'brand_id' => 8,
                'color_id' => 1,
                'product_img' => 'Speaker.jpg',
                'regular_price' => 399.99,
                'sale_price' => 349.99,
                'quantity' => 15,
                'materials' => 'Recycled Plastic',
                'type' => 'Party Speaker',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 25,
                'status' => 'In Stock',
                'descriptions' => '160W RMS powerful JBL Pro Sound, dynamic futuristic light show, 12 hours playback with replaceable battery.',
            ],
            [
                'id' => 36,
                'product_name' => 'Dell Premier Wireless ANC Headset',
                'cate_id' => 6,
                'brand_id' => 4,
                'color_id' => 1,
                'product_img' => 'over-ear.jpg',
                'regular_price' => 249.99,
                'sale_price' => 199.99,
                'quantity' => 28,
                'materials' => 'Memory Foam & Aluminum',
                'type' => 'Business Headset',
                'storage' => 'N/A',
                'RAM' => 'N/A',
                'quantity_sold' => 42,
                'status' => 'In Stock',
                'descriptions' => 'Teams certified ANC headset, noise-canceling boom microphone, up to 78 hours listening time.',
            ],
        ];

        foreach ($products as $p) {
            Products::updateOrCreate(['id' => $p['id']], $p);
        }
    }
}
