version: '3.8'

services:
  laravel-docker:
    container_name: eltromart-docker
    build: .
    volumes:
      - ./eltromartplus_project:/var/www
    ports:
      - 9000:80
    networks:
      - laravel_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: eltromart
      DB_USERNAME: user
      DB_PASSWORD: user123
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eltromart
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - laravel_network
    depends_on:
      - mysql_db

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
