[providers]
providers = ['php', 'node']

[phases.build]
cmds = [
  'composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev',
  'npm ci',
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --seed --force && php artisan serve --host 0.0.0.0 --port ${PORT:-8080}'
